apiVersion: v1
kind: Service
metadata:
  name: cassandra-test
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: cassandra-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-test
  template:
    metadata:
      labels:
        app: cassandra-test
    spec:
      containers:
        - name: cassandra-test
          image: 278088188282.dkr.ecr.us-east-2.amazonaws.com/semantive:latest
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9000

          
